### ISSUE TITLE
aparente falta de CORS na resposta JSON

### ISSUE THREAD

**Issue by ppKrauss** [scieloorg/wayta#18]
O header HTTP de [Access-Control-Allow-Origin](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) aparentemente não está sendo fornecido. É importante para evitar erro de Javascript no acesso via AJAX.

Basta usar `Access-Control-Allow-Origin: *`

**Comment by fabiobatalha** [comment]
@ppKrauss 

Utilizar o exemplo: https://gist.github.com/fabiobatalha/31c43bdefecebea88fa1
