### ISSUE TITLE
Verificar a possibilidade de inserir um campo para sugestões de instituições que não constam na lista

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/wayta#27]
Verificar a possibilidade de implementar um campo no wayta, para sugestão de instituições que não constam no .csv.
As sugestões poderão ser feitas em forma de tícket no github para a equipe analisar a forma normalizada das instituições propostas e adicionar na lista.

**Comment by fabiobatalha** [comment]
As sugestões devem ser feitas pelo github.
